"""initial_schema

Revision ID: bae2f9d39ff5
Revises: 
Create Date: 2026-04-05 02:09:07.458400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae2f9d39ff5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('mandi', sa.String(length=200), nullable=False),
    sa.Column('threshold_price', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_subscriptions_crop'), 'alert_subscriptions', ['crop'], unique=False)
    op.create_index(op.f('ix_alert_subscriptions_user_id'), 'alert_subscriptions', ['user_id'], unique=False)
    op.create_table('model_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('lstm_units', sa.Integer(), nullable=False),
    sa.Column('dropout', sa.Float(), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=False),
    sa.Column('sequence_length', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=False),
    sa.Column('optimized_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_configs_crop'), 'model_configs', ['crop'], unique=False)
    op.create_table('model_diagnostics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('mandi', sa.String(length=200), nullable=False),
    sa.Column('test_name', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('adf_statistic', sa.Float(), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=False),
    sa.Column('critical_1pct', sa.Float(), nullable=True),
    sa.Column('critical_5pct', sa.Float(), nullable=True),
    sa.Column('critical_10pct', sa.Float(), nullable=True),
    sa.Column('is_stationary', sa.Boolean(), nullable=False),
    sa.Column('differencing_applied', sa.Boolean(), nullable=False),
    sa.Column('tested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop', 'mandi', 'test_name', 'stage', name='uq_diag_crop_mandi_test_stage')
    )
    op.create_index(op.f('ix_model_diagnostics_crop'), 'model_diagnostics', ['crop'], unique=False)
    op.create_index(op.f('ix_model_diagnostics_mandi'), 'model_diagnostics', ['mandi'], unique=False)
    op.create_table('raw_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('fetch_date', sa.Date(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_prices_crop'), 'raw_prices', ['crop'], unique=False)
    op.create_index(op.f('ix_raw_prices_fetch_date'), 'raw_prices', ['fetch_date'], unique=False)
    op.create_index(op.f('ix_raw_prices_state'), 'raw_prices', ['state'], unique=False)
    op.create_table('retraining_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('mandi', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('rmse_before', sa.Float(), nullable=True),
    sa.Column('rmse_after', sa.Float(), nullable=True),
    sa.Column('improvement_pct', sa.Float(), nullable=True),
    sa.Column('model_promoted', sa.Boolean(), nullable=False),
    sa.Column('feature_importance_delta', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retraining_logs_crop'), 'retraining_logs', ['crop'], unique=False)
    op.create_index(op.f('ix_retraining_logs_mandi'), 'retraining_logs', ['mandi'], unique=False)
    op.create_table('scrape_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('failed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shap_explanations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('shap_value', sa.Float(), nullable=False),
    sa.Column('feature_value', sa.Float(), nullable=True),
    sa.Column('farmer_label', sa.String(length=200), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shap_explanations_crop'), 'shap_explanations', ['crop'], unique=False)
    op.create_index(op.f('ix_shap_explanations_prediction_date'), 'shap_explanations', ['prediction_date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('weather_obs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('max_temp', sa.Float(), nullable=True),
    sa.Column('min_temp', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district', 'date', name='uq_weather_district_date')
    )
    op.create_index(op.f('ix_weather_obs_date'), 'weather_obs', ['date'], unique=False)
    op.create_index(op.f('ix_weather_obs_district'), 'weather_obs', ['district'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_obs_district'), table_name='weather_obs')
    op.drop_index(op.f('ix_weather_obs_date'), table_name='weather_obs')
    op.drop_table('weather_obs')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shap_explanations_prediction_date'), table_name='shap_explanations')
    op.drop_index(op.f('ix_shap_explanations_crop'), table_name='shap_explanations')
    op.drop_table('shap_explanations')
    op.drop_table('scrape_errors')
    op.drop_index(op.f('ix_retraining_logs_mandi'), table_name='retraining_logs')
    op.drop_index(op.f('ix_retraining_logs_crop'), table_name='retraining_logs')
    op.drop_table('retraining_logs')
    op.drop_index(op.f('ix_raw_prices_state'), table_name='raw_prices')
    op.drop_index(op.f('ix_raw_prices_fetch_date'), table_name='raw_prices')
    op.drop_index(op.f('ix_raw_prices_crop'), table_name='raw_prices')
    op.drop_table('raw_prices')
    op.drop_index(op.f('ix_model_diagnostics_mandi'), table_name='model_diagnostics')
    op.drop_index(op.f('ix_model_diagnostics_crop'), table_name='model_diagnostics')
    op.drop_table('model_diagnostics')
    op.drop_index(op.f('ix_model_configs_crop'), table_name='model_configs')
    op.drop_table('model_configs')
    op.drop_index(op.f('ix_alert_subscriptions_user_id'), table_name='alert_subscriptions')
    op.drop_index(op.f('ix_alert_subscriptions_crop'), table_name='alert_subscriptions')
    op.drop_table('alert_subscriptions')
    # ### end Alembic commands ###
