"""add_phone_language_to_alert_subscriptions

Revision ID: ffe4ba3f60b3
Revises: bae2f9d39ff5
Create Date: 2026-04-05 02:12:38.703079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe4ba3f60b3'
down_revision: Union[str, Sequence[str], None] = 'bae2f9d39ff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_subscriptions', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('alert_subscriptions', sa.Column('language', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_alert_subscriptions_phone_number'), 'alert_subscriptions', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_subscriptions_phone_number'), table_name='alert_subscriptions')
    op.drop_column('alert_subscriptions', 'language')
    op.drop_column('alert_subscriptions', 'phone_number')
    # ### end Alembic commands ###
